# -*- mode: ruby -*-
# vi: set ft=ruby :

# etcd 版本
etcd_version = "2.3.7"

# flannel 版本
flannel_version = "0.7.1-1"

# docker 版本
docker_version = "1.12.6"

# 节点网段
network = "172.72.1"

# 节点数
num_nodes = 3


Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_version = "1706.02"

  # 使用 vagrant hostmanager 命令可以更新宿主机和虚拟机的 hosts 文件
  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true
  config.hostmanager.manage_host = true

  (1..num_nodes).each do |index|
    config.vm.define "centos-flannel-#{index}" do |conf|
      conf.vm.hostname = "centos-flannel-#{index}"
      conf.vm.network :private_network, ip: "#{network}.#{index+10}"

      # 安装 etcd 并设置 flannel CIDR
      if index == 1
        conf.vm.provision "shell", privileged: true, path: "etcd-deploy.sh", args: "#{etcd_version}"
      end

      conf.vm.provision "shell", privileged: true, inline: "yum install -y net-tools"

      # 运行 docker、flannel
      conf.vm.provision "shell" do |s| 
        s.privileged = true
        s.path = "flannel-docker.sh"
        s.args = ["#{flannel_version}", "#{docker_version}", "#{network}.11"]
      end

      conf.vm.provider "virtualbox" do |vbox|
        vbox.name = "centos-flannel-#{index}"
        vbox.cpus = 1.0
        vbox.memory = "256"
      end

    end
  end

end